name: Build BoringSSL with Ninja

on:
  workflow_dispatch:

jobs:
  build-ninja:
    runs-on: windows-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Clone BoringSSL
      run: |
        git clone https://github.com/google/boringssl.git

    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: clang


    - name: Set up CMake + Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc      
        ninjaVersion: latest 

    - name: Configure with CMake (Ninja)
      uses: ilammy/setup-nasm@v1
      env:
          CC: ${{ steps.install_cc.outputs.cc }}
          CXX: ${{ steps.install_cc.outputs.cxx }}
      run: |
        cd boringssl
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
        ninja
   
   
    - name: Upload .lib artifacts
      uses: actions/upload-artifact@v4
      with:
        name: boringssl-libs
        path: |
          boringssl/build/Release/crypto.lib
          boringssl/build/Release/ssl.lib
          boringssl/build/Release/bssl.exe